const blueprints = [
  
  { name:"Bettina", rarity:"Epic", type:"Weapon", maps:["All Maps"], description:"High-tier weapon crates, locked rooms, and boss chests." },
  { name:"Blue Light Stick", rarity:"Common", type:"Utility", maps:["All Maps"], description:"General loot crates." },
  { name:"Aphelion", rarity:"Legendary", type:"Weapon", maps:["Blue Gate","Dam Battlegrounds"], description:"Matriarch core drops and ultra-locked weapon rooms." },
  { name:"Combat Mk.3 (Flanking)", rarity:"Epic", type:"Perk", maps:["All Maps"], description:"High-tier skill caches." },
  { name:"Combat Mk.3 (Aggressive)", rarity:"Epic", type:"Perk", maps:["All Maps"], description:"Elite loot rooms." },
  { name:"Complex Gun Parts", rarity:"Epic", type:"Parts", maps:["All Maps"], description:"Elite weapon caches." },
  { name:"Fire Works Box", rarity:"Rare", type:"Utility", maps:["All Maps"], description:"Event reward containers." }
  { name:"Gas Mine", rarity:"Common", type:"Mine", maps:["All Maps"], description:"Utility crates and underground caches." },
  { name:"Green Light Stick", rarity:"Common", type:"Utility", maps:["All Maps"], description:"Utility crates." },
  { name:"Pulse Mine", rarity:"Uncommon", type:"Mine", maps:["All Maps"], description:"ARC patrol loot and tech crates." },
  { name:"Seeker Grenade", rarity:"Uncommon", type:"Grenade", maps:["All Maps"], description:"Utility crates and raider caches." },
  { name:"Looting Mk.3 (Survivor)", rarity:"Epic", type:"Perk", maps:["All Maps"], description:"Utility vaults." },
  { name:"Angled Grip II", rarity:"Uncommon", type:"Mod", maps:["All Maps"], description:"Weapon crates and residential lockers." },
  { name:"Angled Grip III", rarity:"Rare", type:"Mod", maps:["All Maps"], description:"High-tier weapon rooms." },
  { name:"HullCracker", rarity:"Epic", type:"Weapon", maps:["All Maps"], description:"Weapon crates in high-loot zones." },
  { name:"Anvil", rarity:"Uncommon", type:"Weapon", maps:["All Maps"], description:"High-tier weapon crates, locked rooms." },

  { name:"Barricade Kit", rarity:"Uncommon", type:"Utility", maps:["All Maps"], description:"Construction lockers." },
  { name:"Blaze Grenade", rarity:"Rare", type:"Grenade", maps:["All Maps"], description:"Explosives lockers and event rewards." },
  { name:"Bobcat", rarity:"Epic", type:"Weapon", maps:["All Maps"], description:"Security rooms, elite ARC zones." },
  { name:"Osprey", rarity:"Rare", type:"Weapon", maps:["All Maps"], description:"Weapon lockers and event reward crates." },
  { name:"Burletta", rarity:"Uncommon", type:"Weapon", maps:["All Maps"], description:"Residential loot rooms and raider caches." },
  { name:"Compensator II", rarity:"Uncommon", type:"Mod", maps:["All Maps"], description:"Weapon crates and security lockers." },
  { name:"Compensator III", rarity:"Rare", type:"Mod", maps:["All Maps"], description:"Locked armories and event crates." },
  { name:"Defibrillator", rarity:"Rare", type:"Utility", maps:["All Maps"], description:"Medical vaults and event rewards." },

  { name:"Equalizer", rarity:"Legendary", type:"Weapon", maps:["All Maps"], description:"Locked weapon crates and boss areas." },
  { name:"Extended Barrel", rarity:"Epic", type:"Mod", maps:["All Maps"], description:"Weapon vaults and hangar lockers." },
  { name:"Extended Light Mag II", rarity:"Uncommon", type:"Mod", maps:["All Maps"], description:"Weapon crates and raider stashes." },
  { name:"Extended Light Mag III", rarity:"Rare", type:"Mod", maps:["All Maps"], description:"High-tier loot rooms." },
  { name:"Extended Medium Mag II", rarity:"Uncommon", type:"Mod", maps:["All Maps"], description:"Weapon crates." },
  { name:"Extended Medium Mag III", rarity:"Rare", type:"Mod", maps:["All Maps"], description:"Elite containers." },
  { name:"Extended Shotgun Mag II", rarity:"Uncommon", type:"Mod", maps:["All Maps"], description:"Shotgun lockers and close-range zones." },
  { name:"Extended Shotgun Mag III", rarity:"Rare", type:"Mod", maps:["All Maps"], description:"High-tier shotgun caches." },
  { name:"Remote Raider Flare", rarity:"Uncommon", type:"Utility", maps:["All Maps"], description:"Recon caches." },
  { name:"Heavy Gun Parts", rarity:"Rare", type:"Parts", maps:["All Maps"], description:"ARC drop zones." },
  { name:"Venator", rarity:"rare", type:"Weapon", maps:["All Maps"], description:"High-tier ARC patrol zones." },
  { name:"Il Toro", rarity:"uncommon", type:"Weapon", maps:["All Maps"], description:"Weapon caches in underground routes." },
  { name:"Jolt Mine", rarity:"Rare", type:"Mine", maps:["All Maps"], description:"Power stations and event chests." },
  { name:"Explosive Mine", rarity:"Rare", type:"Mine", maps:["All Maps"], description:"Explosives lockers and raider caches." },
  { name:"Jupiter", rarity:"Legendary", type:"Weapon", maps:["All Maps"], description:"Weapon lockers in industrial zones." },
  { name:"Light Gun Parts", rarity:"Rare", type:"Parts", maps:["All Maps"], description:"Weapon salvage crates." },
  { name:"Lightweight Stock", rarity:"Epic", type:"Mod", maps:["All Maps"], description:"Weapon lockers." },
  { name:"Looting Mk.3 (SafeKeeper)", rarity:"Epic", type:"Perk", maps:["All Maps"], description:"Event reward crates." },
  { name:"Lure Grenade", rarity:"Uncommon", type:"Grenade", maps:["All Maps"], description:"Utility containers and loot rooms." },
  { name:"Medium Gun Parts", rarity:"Rare", type:"Parts", maps:["All Maps"], description:"Industrial loot containers." },
  { name:"Torrente", rarity:"Rare", type:"Weapon", maps:["All Maps"], description:"Security checkpoints and vault rooms." },
  { name:"Muzzle Brake II", rarity:"Uncommon", type:"Mod", maps:["All Maps"], description:"Weapon lockers." },
  { name:"Muzzle Brake III", rarity:"Rare", type:"Mod", maps:["All Maps"], description:"Elite armories." },
  { name:"Padded Stock", rarity:"Epc", type:"Mod", maps:["All Maps"], description:"Utility crates." },
  { name:"Shotgun Choke II", rarity:"Uncommon", type:"Mod", maps:["All Maps"], description:"Shotgun crates." },
  { name:"Shotgun Choke III", rarity:"Rare", type:"Mod", maps:["All Maps"], description:"High-tier CQB zones." },
  { name:"Shotgun Silencer", rarity:"Epic", type:"Mod", maps:["All Maps"], description:"Rare shotgun lockers." },
  { name:"Showstopper", rarity:"Rare", type:"Weapon", maps:["All Maps"], description:"Shotgun crates in close-quarters zones." },
  { name:"Silencer I", rarity:"Uncommon", type:"Mod", maps:["All Maps"], description:"General weapon loot." },
  { name:"Silencer II", rarity:"Rare", type:"Mod", maps:["All Maps"], description:"Security lockers." },
  { name:"Snap Hook", rarity:"Legendary", type:"Utility", maps:["All Maps"], description:"Utility lockers and traversal crates." },
  { name:"Stable Stock II", rarity:Uncommon", type:"Mod", maps:["All Maps"], description:"General loot." },
  { name:"Stable Stock III", rarity:"Rare", type:"Mod", maps:["All Maps"], description:"Elite weapon caches." },
  { name:"Tagging Grenade", rarity:"Rare", type:"Grenade", maps:["All Maps"], description:"Recon supply crates." },
  { name:"Tempest", rarity:"Epic", type:"Weapon", maps:["All Maps"], description:"Event reward crates and locked armories." },
  { name:"Trigger Nade", rarity:"Rare", type:"Grenade", maps:["All Maps"], description:"Explosives lockers and industrial crates." },
  { name:"Vertical Grip II", rarity:"Uncommon", type:"Mod", maps:["All Maps"], description:"Weapon crates." },
  { name:"Vertical Grip III", rarity:"Rare", type:"Mod", maps:["All Maps"], description:"High-tier weapon rooms." },
  { name:"Vita Shot", rarity:"Rare", type:"Consumable", maps:["All Maps"], description:"Medical lockers." },
  { name:"Vita Spray", rarity:"Epic", type:"Consumable", maps:["All Maps"], description:"Emergency rooms and med crates." },
  { name:"Vulcano", rarity:"Epic", type:"Weapon", maps:["All Maps"], description:"Elite containers in ARC hotspots." },
  { name:"Wolfpack", rarity:"Epic", type:"Weapon", maps:["All Maps"], description:"Ultra-rare weapon caches and boss events." },
  { name:"Red Light Stick", rarity:"Common", type:"Utility", maps:["All Maps"], description:"General loot." },
  { name:"Smoke Grenade", rarity:"Rare", type:"Grenade", maps:["All Maps"], description:"General utility loot containers." },
  { name:"Tactical Mk.3 (Revival)", rarity:"Epic", type:"Perk", maps:["All Maps"], description:"High-risk zones." },
  { name:"Deadline", rarity:"Rare", type:"Weapon", maps:["All Maps"], description:"End-game loot chests and boss events." },
  { name:"Trailblazer Grenade", rarity:"Rare", type:"Grenade", maps:["All Maps"], description:"High-loot crates near ARC zones." },
  { name:"Tactical Mk.3 (Defensive)", rarity:"Epic", type:"Perk", maps:["All Maps"], description:"Elite caches." },
  { name:"Tactical Mk.3 (Healing)", rarity:"Epic", type:"Perk", maps:["All Maps"], description:"Medical vaults." },
  { name:"Yellow Light Stick", rarity:"Common", type:"Utility", maps:["All Maps"], description:"Utility loot." },

];

